package com.example.tallking.entity;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table postdto
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class Postdt {



    private String avatar;



    private Boolean favorite;


    private Integer level;


    private Boolean like;


    private String nickname;


    private Integer userid;


    private String username;

    private Post post;





}