package com.example.tallking.entity;

import com.baomidou.mybatisplus.annotation.TableName;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.util.List;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table postviewdto
 */

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@TableName("postviewdto")
public class Postviewdto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postviewdto.favorite
     *
     * @mbg.generated
     */


    @Column(name = "favorite")
    private Boolean favorite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postviewdto.like
     *
     * @mbg.generated
     */
    @Column(name = "like")
    private Boolean like;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postviewdto.favorite
     *
     * @return the value of postviewdto.favorite
     *
     * @mbg.generated
     */

    @Transient
    Postdt postDto;

    @Transient
    List<Tag> tagList;




}