package com.example.tallking.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.*;

import javax.persistence.*;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table post
 */
@AllArgsConstructor
@NoArgsConstructor
@Data
@Builder
@TableName("post")
public class Post {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.id
     *
     * @mbg.generated
     */
    @TableId(value = "id",type = IdType.AUTO)
    //@GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.category
     *
     * @mbg.generated
     */
    @Column(name = "category")
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.categoryId
     *
     * @mbg.generated
     */
    @Column(name = "categoryid")
    private Integer categoryid;
//Error invoking SqlProvider method 'public java.lang.String tk.mybatis.mapper.mapperhelper.MapperTemplate.dynamicSQL(java.lang.Object)' with specify parameter 'class com.example.tallking.entity.Post'
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.content
     *
     * @mbg.generated
     */
    @Column(name = "content")
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.createdAt
     *
     * @mbg.generated
     */
    @Column(name = "createdat")
    private String createdat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.favoriteCount
     *
     * @mbg.generated
     */
    @Column(name = "favoritecount")
    private Integer favoritecount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.likeCount
     *
     * @mbg.generated
     */
    @Column(name = "likecount")
    private Integer likecount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.parentId
     *
     * @mbg.generated
     */
    @Column(name = "parentid")
    private Integer parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.recommend
     *
     * @mbg.generated
     */

    @Column(name = "recommend")
    private Integer recommend;





    @Column(name = "tagid")
    private Integer tagid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.replyCount
     *
     * @mbg.generated
     */

    @Column(name = "replycount")
    private Integer replycount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.status
     *
     * @mbg.generated
     */
    @Column(name = "status")
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.title
     *
     * @mbg.generated
     */

    @Column(name = "title")
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.updatedAt
     *
     * @mbg.generated
     */
    @Column(name = "updatedat")
    private String updatedat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.userId
     *
     * @mbg.generated
     */
    @Column(name = "userid")
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.viewCount
     *
     * @mbg.generated
     */
    @Column(name = "viewcount")
    private Integer viewcount;


}