package com.example.tallking.entity;

import com.baomidou.mybatisplus.annotation.TableName;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table postsearchdto
 */
@AllArgsConstructor
@NoArgsConstructor
@Data
@Builder
public class postSearchDto {



    private Integer categoryid;


    private String createdBegin;


    private String createdEnd;

    private Integer ids;


    private Integer limit;

    private Integer page;


    private Integer recommend;


    private Integer status;


    private String tag;


    private String title;


    private Integer total;


    private Integer userid;

    private String username;









}