package com.example.tallking.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table postdto
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@TableName("postdto")
public class Postdto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postdto.avatar
     *
     * @mbg.generated
     */
    @TableId(value = "id",type = IdType.AUTO)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;



    @Column(name = "avatar")
    private String avatar;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postdto.favorite
     *
     * @mbg.generated
     */
    @Column(name = "favorite")
    private String favorite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postdto.level
     *
     * @mbg.generated
     */
    @Column(name = "level")
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postdto.like
     *
     * @mbg.generated
     */
    @Column(name = "like")
    private String like;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postdto.nickname
     *
     * @mbg.generated
     */
    @Column(name = "nickname")
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postdto.userId
     *
     * @mbg.generated
     */
    @Column(name = "userid")
    private Integer userid;

    @Column(name = "postid")
    private Integer postid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postdto.username
     *
     * @mbg.generated
     */
    @Column(name = "username")
    private String username;



    @Transient
    private Post post;




    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Post getPost() {
        return post;
    }

    public void setPost(Post post) {
        this.post = post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postdto.avatar
     *
     * @return the value of postdto.avatar
     *
     * @mbg.generated
     */








    public String getAvatar() {
        return avatar;
    }




    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column postdto.avatar
     *
     * @param avatar the value for postdto.avatar
     *
     * @mbg.generated
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postdto.favorite
     *
     * @return the value of postdto.favorite
     *
     * @mbg.generated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column postdto.favorite
     *
     * @param favorite the value for postdto.favorite
     *
     * @mbg.generated
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postdto.level
     *
     * @return the value of postdto.level
     *
     * @mbg.generated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column postdto.level
     *
     * @param level the value for postdto.level
     *
     * @mbg.generated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postdto.like
     *
     * @return the value of postdto.like
     *
     * @mbg.generated
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column postdto.like
     *
     * @param like the value for postdto.like
     *
     * @mbg.generated
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postdto.nickname
     *
     * @return the value of postdto.nickname
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column postdto.nickname
     *
     * @param nickname the value for postdto.nickname
     *
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postdto.userId
     *
     * @return the value of postdto.userId
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column postdto.userId
     *
     * @param userid the value for postdto.userId
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postdto.username
     *
     * @return the value of postdto.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column postdto.username
     *
     * @param username the value for postdto.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }
}