package com.example.tallking.entity;

import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Builder;
import lombok.Data;

import javax.persistence.*;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table userdto
 */
@Builder
@Data
@TableName("userdto")
public class UserDto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userdto.id
     *
     * @mbg.generated
     */

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userdto.avatar
     *
     * @mbg.generated
     */
    @Column(name = "avatar")
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userdto.createdAt
     *
     * @mbg.generated
     */
    @Column(name = "createdat")
    private String createdat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userdto.mobile
     *
     * @mbg.generated
     */

    @Column(name = "mobile")
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userdto.nickname
     *
     * @mbg.generated
     */

    @Column(name = "nickname")
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userdto.username
     *
     * @mbg.generated
     */

    @Column(name = "username")
    private String username;

    @Column(name = "password")
    private String password;


    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public String toString() {
        return "Userdto{" +
                "id=" + id +
                ", avatar='" + avatar + '\'' +
                ", createdat='" + createdat + '\'' +
                ", mobile='" + mobile + '\'' +
                ", nickname='" + nickname + '\'' +
                ", username='" + username + '\'' +
                ", password='" + password + '\'' +
                '}';
    }

    public UserDto() {
    }

    public UserDto(Integer id, String avatar, String createdat, String mobile, String nickname, String username, String password) {
        this.id = id;
        this.avatar = avatar;
        this.createdat = createdat;
        this.mobile = mobile;
        this.nickname = nickname;
        this.username = username;
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userdto.id
     *
     * @return the value of userdto.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userdto.id
     *
     * @param id the value for userdto.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userdto.avatar
     *
     * @return the value of userdto.avatar
     *
     * @mbg.generated
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userdto.avatar
     *
     * @param avatar the value for userdto.avatar
     *
     * @mbg.generated
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userdto.createdAt
     *
     * @return the value of userdto.createdAt
     *
     * @mbg.generated
     */
    public String getCreatedat() {
        return createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userdto.createdAt
     *
     * @param createdat the value for userdto.createdAt
     *
     * @mbg.generated
     */
    public void setCreatedat(String createdat) {
        this.createdat = createdat == null ? null : createdat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userdto.mobile
     *
     * @return the value of userdto.mobile
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userdto.mobile
     *
     * @param mobile the value for userdto.mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userdto.nickname
     *
     * @return the value of userdto.nickname
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userdto.nickname
     *
     * @param nickname the value for userdto.nickname
     *
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userdto.username
     *
     * @return the value of userdto.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userdto.username
     *
     * @param username the value for userdto.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }
}