package com.example.tallking.entity;

import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Builder;
import lombok.Data;

import javax.persistence.*;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table userlogindto
 */
@Data
@Builder
@TableName("userlogindto")
public class UserLoginDto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlogindto.avatar
     *
     * @mbg.generated
     */

    @Column(name = "avatar")
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlogindto.username
     *
     * @mbg.generated
     */
    @Column(name = "username")
    private String username;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlogindto.avatar
     *
     * @return the value of userlogindto.avatar
     *
     * @mbg.generated
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlogindto.avatar
     *
     * @param avatar the value for userlogindto.avatar
     *
     * @mbg.generated
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlogindto.username
     *
     * @return the value of userlogindto.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlogindto.username
     *
     * @param username the value for userlogindto.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }
}