server:
  port: 8088
spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tallking?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: root
    hikari:
      max-lifetime: 1000000
  thymeleaf:
    cache: false #关闭缓存
  #    prefix: classpath:/static/**
  #    suffix: .html
  #    mode: HTML5
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /static/uploads/**
  #  web:
#    resources:
#      static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/, classpath:/uploads/
  view:
    suffix: .html
    prefix: /end/page
  web:
    resources:
      static-locations: file:${upload.path}

upload:
  path: ${user.dir}/uploads/

mybatis:
  #  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.tallking.entity
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

authority:
  info: '[]'

logging:
  file:
    path: log
    name: log/my.log
  level:
    com:
      javaclimb:
        dao: debug



#        resources:
#        static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/, classpath:/templates/
#